const CONSTANTS = {
  ADD_CARD: "ADD_CARD",
  ADD_LIST: "ADD_LIST",
  EDIT_CARD: "EDIT_CARD",
  EDIT_LIST_TITLE: "EDIT_LIST_TITLE",
  DELETE_CARD: "DELETE_CARD",
  DELETE_LIST: "DELETE_LIST",
  UPDATE_CARD: "UPDATE_CARD",
};

export default CONSTANTS;
